### ISSUE TITLE
Files not included in the release tar .

### ISSUE THREAD

**Issue by b-aaz** [indgy/refind-bsd-black#2]
Hi !
Thanks for the grate theme .
Three small issues :
1. The `background.png` is not included in the release tar .
2. The `fonts/liberation-mono-regular-14.png` can't be found in the repo but it is in the `theme.conf` .
3. Some of the icons like the `func_shutdown.png` and `func_install.png` have some non transparent edges/outlines  .

**Comment by indgy** [comment]
Thanks for pointing those issues out, I'll update the release tar soon.

**Comment by indgy** [comment]
This is fixed in the latest release available here https://github.com/indgy/refind-bsd-black/releases/tag/0.1.1
